name: continuous
on:
  push:
    branches: [ "main" , "develop" ]
  pull_request:
    branches: [ "main" , "develop"]
env:
  CARGO_TERM_COLOR: always
jobs:
  continuous:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: deps 
      run: sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin curl fd-find git docker-buildx-plugin packer && packer plugins install github.com/hashicorp/docker
    - name: continuous
      run: git clone https://github.com/taishingi/continuous-template.git continuous && cd continuous/rust && ./scripts-gen "github.com" "otechdo" "zazen" "${GITHUB_REF##*/}" "4" && packer validate . && packer build .
